### ISSUE TITLE
pre-trained model? 

### ISSUE THREAD

**Issue by danyaljj** [dev-chauhan/PQG-pytorch#2]
Hello there, 
Do you have the pretrained models available somewhere?

**Comment by dev-chauhan** [comment]
I have saved tar files of models which I have trained.

**Comment by tim5go** [comment]
@dev-chauhan 
Same here, would you mind sharing a pre-trained model?

**Comment by dev-chauhan** [comment]
https://drive.google.com/uc?export=download&id=1_6yXi145X28VRmQGI7cyPJRXYoUZGKwX
This is EDLPS trained for 150 epoch using which results are generated in README.md
