### ISSUE TITLE
Predict with new paraphrase examples

### ISSUE THREAD

**Issue by ak-kumar-v** [dev-chauhan/PQG-pytorch#6]
How can i test the model with different paraphrase sentence after training?

**Comment by dev-chauhan** [comment]
You just have to make a custom dataset in PyTorch just like in `dataloader.py` if you are trying with a different paraphrase dataset. You can see in `train_*.py` files that show how to evaluate the model or how to get predicted paraphrase.

**Comment by srinivasraman18** [comment]
Hi @dev-chauhan ,
Can you pls tell me if it is possible to use a different test dataset on your pretrained model or do i need to retrain the model?
Thank you.

**Comment by ak-kumar-v** [comment]
You have to train the model first, the model will be saved in a directory "save" with .pt extension(have to create this, as mentioned in the README), then use checkpoint to load model and evaluate your dataset. I tried it, but output doesn't work well. If you get any solution kindly post here too
